### ISSUE TITLE
Thunderbolt help!

### ISSUE THREAD

**Issue by hoaug-tran** [dikamsiyoung/Lenovo-Yoga-720-15IKB-Hackintosh#5]
hi, hope you have a good day.

can you guide me to patch thunderbolt for the machine?, i have the same thunderbolt device as you: Intel JHL6540. or if you don't have enough time, can you help me build SSDT for it. thank you so much!

below is my DSDT
[DSDT.zip](https://github.com/dikamsiyoung/Lenovo-Yoga-720-15IKB-Hackintosh/files/12187258/DSDT.zip)

**Comment by dikamsiyoung** [comment]
Have you read the section about Thunderbolt? A thunderbolt SSDT is already provided in the repo

**Comment by hoaug-tran** [comment]
thank you for reply me, but the SSDT of thunderbolt is not working with my laptop

**Comment by dikamsiyoung** [comment]
Hi, where you able to resolve this issue?
