### ISSUE TITLE
Installation cannot be completed.

### ISSUE THREAD

**Issue by wp1018347903** [dikamsiyoung/Lenovo-Yoga-720-15IKB-Hackintosh#7]
My computer configuration is the same as yours, but I can't proceed to the installation stage. I hope you can help me.
During the first stage of installation, there is an error code as shown in figure 1, I got a friend to fix the problem, however, after the first stage of installation, when I go to the second stage, it reboots infinitely with an error code as shown in figure 2.

![1](https://github.com/dikamsiyoung/Lenovo-Yoga-720-15IKB-Hackintosh/assets/57518576/d5a79fc9-924d-42c0-88a4-006aadef2723)
![2](https://github.com/dikamsiyoung/Lenovo-Yoga-720-15IKB-Hackintosh/assets/57518576/b521dd8d-0bb6-4689-8410-ecac3b32287e)

**Comment by wp1018347903** [comment]
problem solved！

Misc -> Security -> SecureBootModel -> Disabled

**Comment by dikamsiyoung** [comment]
Awesome! Glad you had this fixed!
