### ISSUE TITLE
Network card

### ISSUE THREAD

**Issue by richibrics** [dikamsiyoung/Lenovo-Yoga-720-15IKB-Hackintosh#8]
Hi, I saw you changed your wireless card to a Broadcom. Did you mod the bios to avoid the whitelist or was it supported natively ? 
Currently I'm using a Lenovo Yoga c640 but I can't find any information about wireless cards. Thank you

**Comment by dikamsiyoung** [comment]
Hi Richibrics. No, I didn't have to tinker around with the BIOS, the card worked natively out of the box 👍
